name: Secrets scan

on:
  push:
    branches: [ main, master, feature/** ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks scanner
        uses: zricethezav/gitleaks-action@v1
        with:
          args: --redact


